/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jackson.coma;

import jackson.coma.JacksonComa.Car;

/**
 *
 * @author OWNER
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    Car myCar;
    public GUI() {
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rRed = new javax.swing.JRadioButton();
        rWhite = new javax.swing.JRadioButton();
        rBlack = new javax.swing.JRadioButton();
        rGreen = new javax.swing.JRadioButton();
        lblMake = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblChoice = new javax.swing.JLabel();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        btnAddCar = new javax.swing.JButton();
        btnChangeCar = new javax.swing.JButton();
        btnSpeedUp = new javax.swing.JButton();
        btnBrake = new javax.swing.JButton();
        lblColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rRed.setText("RED");

        rWhite.setText("WHITE");
        rWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rWhiteActionPerformed(evt);
            }
        });

        rBlack.setText("BLACK");

        rGreen.setText("GREEN");

        lblMake.setText("MAKE");

        lblModel.setText("MODEL");

        lblChoice.setText("Choose Options");

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        btnAddCar.setText("Add Car");

        btnChangeCar.setText("Modify Car");
        btnChangeCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeCarActionPerformed(evt);
            }
        });

        btnSpeedUp.setText("Getty Up");

        btnBrake.setText("Whoa Mule");
        btnBrake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrakeActionPerformed(evt);
            }
        });

        lblColor.setText("COLOR:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rRed, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rWhite)
                                .addGap(8, 8, 8)
                                .addComponent(rBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rGreen)
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddCar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnChangeCar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnSpeedUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBrake))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMake)
                            .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblModel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblChoice)
                                            .addComponent(lblColor))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblChoice)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMake)
                    .addComponent(lblModel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblColor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rGreen)
                            .addComponent(rBlack)
                            .addComponent(rWhite)
                            .addComponent(rRed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddCar)
                            .addComponent(btnChangeCar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSpeedUp)
                            .addComponent(btnBrake))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rWhiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rWhiteActionPerformed

    private void btnChangeCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeCarActionPerformed

    private void btnBrakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrakeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCar;
    private javax.swing.JButton btnBrake;
    private javax.swing.JButton btnChangeCar;
    private javax.swing.JButton btnSpeedUp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChoice;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblModel;
    private javax.swing.JRadioButton rBlack;
    private javax.swing.JRadioButton rGreen;
    private javax.swing.JRadioButton rRed;
    private javax.swing.JRadioButton rWhite;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
// Call groupButton method
        groupButton();
        // Make the output box un-editable, for nice formatting
        txtOutput.setEditable(false);
        // Select the color white buy default, you're allowed to change of course.
        rWhite.setSelected(true);
        // disable the edit car button, since you need to create a car first.
        btnChangeCar.setEnabled(false);
        // disable the speed button since there is no car yet.
        btnSpeedUp.setEnabled(false);
        // disable the brake button since there is no car yet.
        btnBrake.setEnabled(false);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnAddCar = new javax.swing.JButton();
        txtModel = new javax.swing.JTextField();
        txtMake = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        btnSpeedUp = new javax.swing.JButton();
        btnBrake = new javax.swing.JButton();
        lblMake = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblChoice = new javax.swing.JLabel();
        btnChangeCar = new javax.swing.JButton();
        rWhite = new javax.swing.JRadioButton();
        rRed = new javax.swing.JRadioButton();
        rGreen = new javax.swing.JRadioButton();
        rBlack = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnAddCar.setText("Add Car");
        btnAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarActionPerformed(evt);
            }
        });

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        txtOutput.setFocusable(false);
        jScrollPane1.setViewportView(txtOutput);

        btnSpeedUp.setText("Accelerate");
        btnSpeedUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeedUpActionPerformed(evt);
            }
        });

        btnBrake.setText("Brake");
        btnBrake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrakeActionPerformed(evt);
            }
        });

        lblMake.setText("Make:");

        lblModel.setText("Model:");

        lblColor.setText("Color:");

        lblChoice.setText("CONFIGURE CAR:");

        btnChangeCar.setText("Edit Car");
        btnChangeCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeCarActionPerformed(evt);
            }
        });

        rWhite.setText("WHITE");

        rRed.setText("RED");

        rGreen.setText("GREEN");

        rBlack.setText("BLACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblChoice)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnChangeCar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSpeedUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBrake, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblColor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(rWhite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rRed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rGreen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rBlack))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMake)
                                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblModel))))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblChoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMake)
                    .addComponent(lblModel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rWhite)
                    .addComponent(rRed)
                    .addComponent(rGreen)
                    .addComponent(rBlack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChangeCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpeedUp)
                    .addComponent(btnBrake))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    //******************************************************
    //*** Method Name: AddCar button click
    //*** Method Author: Ali Alhachamy
    //******************************************************
    //*** Purpose of the Method: this method will add a car to an object if the user
    //*** inputs the required fields    
    //*** Method parameters: none
    //*** Return value: void
    //******************************************************
    //*** Date: 9/19/17
    //******************************************************
    private void btnAddCarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        // If the textboxes are empty.
        if (txtMake.getText().isEmpty() || txtModel.getText().isEmpty()){
            // Show an error message.
            JOptionPane.showMessageDialog(null, "Invalid Input. \nMake or Model is empty.");
        }
        // else
        else{
            // Check which color is selected
            if(rWhite.isSelected()){
              // Pass the make, model, and color to the constructor.
            myCar = new Car(txtMake.getText(), txtModel.getText(),
                            getColor(rWhite.getText()));
            }
            
            // Check which color is selected
            else if(rRed.isSelected()){
                // Pass the make, model, and color to the constructor.
            myCar = new Car(txtMake.getText(), txtModel.getText(),
                            getColor(rRed.getText()));
            }
            
            // Check which color is selected
            else if(rGreen.isSelected()){
                // Pass the make, model, and color to the constructor.
            myCar = new Car(txtMake.getText(), txtModel.getText(),
                            getColor(rGreen.getText()));
            }
            
            // Check which color is selected
            else if(rBlack.isSelected()){
                // Pass the make, model, and color to the constructor.
            myCar = new Car(txtMake.getText(), txtModel.getText(),
                            getColor(rBlack.getText()));
            }
            
            // disable the add car button
            btnAddCar.setEnabled(false);
            // enable the edit car button.
            btnChangeCar.setEnabled(true);
            // enable speed button.
            btnSpeedUp.setEnabled(true);
            // enable brake button.
            btnBrake.setEnabled(true);
            
            // call output method to display output.
            output();   
        }
    }                                         

    
    //******************************************************
    //*** Method Name: ChangeCar button click
    //*** Method Author: Ali Alhachamy
    //******************************************************
    //*** Purpose of the Method: this method allows the user to edit the car once
    //*** once it's created
    //*** Method parameters: none 
    //*** Return value: none
    //******************************************************
    //*** Date: 9/19/17
    //******************************************************
    private void btnChangeCarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        
        // If textboxes are empty.
        if (txtMake.getText().isEmpty() || txtModel.getText().isEmpty()){
            // Display error message.
            JOptionPane.showMessageDialog(null, "Invalid Input. \nMake or Model is empty.");
        }
        // else
        else{
            // Set the text input to the car class make using setters
            myCar.setMake(txtMake.getText());
            // Set the text input to the car class model using setters
            myCar.setModel(txtModel.getText());
        
            // Do the same thing with color but since it's a radio button
            // it had to be a series of if statements
            if(rWhite.isSelected()){
                myCar.setColor(getColor(rWhite.getText()));
            }
            else if(rRed.isSelected()){
                myCar.setColor(getColor(rRed.getText()));
            }
            else if(rGreen.isSelected()){
                myCar.setColor(getColor(rGreen.getText()));
            }
            else if(rBlack.isSelected()){
                myCar.setColor(getColor(rBlack.getText()));
            }
            
            // call output method to display output.
            output();   
        }
    }                                            

    //******************************************************
    //*** Method Name: SpeedUp button click
    //*** Method Author: Ali Alhachamy
    //******************************************************
    //*** Purpose of the Method: speeds up the car by calling a member method
    //*** Method parameters: none
    //*** Return value: none
    //******************************************************
    //*** Date: 9/19/17
    //******************************************************
    private void btnSpeedUpActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // Call accelerate method.
        myCar.accelerate();
        // display output for the user.
        txtOutput.append("\nSpeeding: " + myCar.getSpeed());
    }                                          

    
    //******************************************************
    //*** Method Name: Brake button action
    //*** Method Author: Ali Alhachamy
    //******************************************************
    //*** Purpose of the Method: brakes the car by calling a member method
    //*** Method parameters: none
    //*** Return value: none
    //******************************************************
    //*** Date: 9/19/17
    //******************************************************
    private void btnBrakeActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Call break member method
        myCar.brake();
        // if car isn't moving, display message.
        if(myCar.getSpeed() == 0){
            txtOutput.append("\nThe car is not moving. ");
        }
        // else
        else{
            // display the the speed as the car is slowing down
            txtOutput.append("\nBreaking: " + myCar.getSpeed());   
        }
    }                                        

    
    //******************************************************
    //*** Method Name: getColor
    //*** Method Author: Ali Alhachamy
    //******************************************************
    //*** Purpose of the Method: this method returns a color, that color is then
    //*** passed to the car class and stored in the Car variable.
    //*** Method parameters: String val
    //*** Return value: Color
    //******************************************************
    //*** Date: 9/19/17
    //******************************************************

    private Color getColor(String val){
        // the method will recieve the string name of the radio box
        // depending on which radio box it is, it will send a specific color.
        switch(val){
            // returns white
            case "WHITE":
                return Color.WHITE;
            // returns red    
            case "RED":
                return Color.RED;
            // returns Green
            case "GREEN":
                return Color.GREEN;
            // returns green
            case "GREEN":
                return Color.GREEN;
            // returns black
            case "BLACK":
                return Color.BLACK;
        }
        // needed so the ide would shut up
        return null;
    }
    
    
    //******************************************************
    //*** Method Name: output
    //*** Method Author: Ali Alhachamy
    //******************************************************
    //*** Purpose of the Method: This method will print output
    //*** Method parameters: none
    //*** Return value: void
    //******************************************************
    //*** Date: 9/19/19
    //******************************************************

    private void output(){
            // Display make and model
            txtOutput.setText("Make: " + myCar.getMake() + "\nModel: " + myCar.getModel() + "\n");
            
            // display all the different colors
            if(rWhite.isSelected()){
            txtOutput.append("Color: White");
            }
            else if(rRed.isSelected()){
            txtOutput.append("Color: Red");
            }
            else if(rGreen.isSelected()){
           txtOutput.append("Color: Green");
            }
            else if(rBlack.isSelected()){
            txtOutput.append("Color: Black");
            }
            
    }
    
    
    //******************************************************
    //*** Method Name: groupButton
    //*** Method Author: Ali Alhachamy
    //******************************************************
    //*** Purpose of the Method: this method sets all the radio buttons together
    //*** so you can only choose one at a time.
    //*** Method parameters: none
    //*** Return value: void
    //******************************************************
    //*** Date: 9/19/17
    //******************************************************
    private void groupButton(){
        // create an object of type ButtonGroup.
        ButtonGroup bg = new ButtonGroup();
        // add all the radio buttons to it
        bg.add(rWhite);
        bg.add(rBlack);
        bg.add(rGreen);
        bg.add(rRed);
    }
    
    //  pre-created main
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAddCar;
    private javax.swing.JButton btnBrake;
    private javax.swing.JButton btnChangeCar;
    private javax.swing.JButton btnSpeedUp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblChoice;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblModel;
    private javax.swing.JRadioButton rBlack;
    private javax.swing.JRadioButton rGreen;
    private javax.swing.JRadioButton rRed;
    private javax.swing.JRadioButton rWhite;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration                   
}
